/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

/**
 *
 * @author 01 Capital
 */
public class TelaEntrar extends javax.swing.JPanel {

    // Botão toggle — adicionado programaticamente, não gerado pelo Form Editor
    private JButton btnToggleTema;

    /**
     * Creates new form TelaEntrar
     */
    public TelaEntrar() {
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/iamgens/1.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("BEM-VINDO DE VOLTA");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Consulte o estado da Inscricao ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Acompanhe sua Canditatura sem sair de casa");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Veja sua posicao no Ranking");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Receba o resultado da Seleccao ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel4)
                    .addContainerGap(90, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(95, 95, 95)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(215, 215, 215)
                    .addComponent(jLabel4)
                    .addContainerGap(506, Short.MAX_VALUE)))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Entrar");

        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Email");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Senha");

        jPasswordField1.setBackground(new java.awt.Color(102, 102, 102));
        jPasswordField1.setText("jPasswordField1");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/iamgens/login.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setText("ENTRAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        JButton btnVoltar = new JButton("<- Voltar");
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(e -> {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            if (frame != null) {
                frame.setContentPane(new TelaInicial());
                frame.revalidate();
                frame.repaint();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnVoltar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(19, 19, 19)))
                .addGap(59, 59, 59)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addContainerGap(178, Short.MAX_VALUE))
        );

    }// </editor-fold>//GEN-END:initComponents

    // =========================================================================
    // POST-INIT — adicionado manualmente, NÃO toca no código gerado acima
    // REGRA: nunca chamar setLayout() nem remover componentes existentes
    // =========================================================================

    private void postInit() {
        // 1. Sidebar — textos brancos e ícone limpo
        jLabel1.setText("");
        jLabel2.setForeground(Color.WHITE);
        jLabel3.setForeground(new Color(0xCBD5E1));
        jLabel4.setForeground(new Color(0xCBD5E1));
        jLabel5.setForeground(new Color(0xCBD5E1));
        jLabel6.setForeground(new Color(0xCBD5E1));

        // 2. Formulário — fontes e bordas arredondadas
        jLabel7.setFont(new Font("Segoe UI", Font.BOLD, 22));
        jLabel8.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        jLabel9.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        jTextField1.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        jTextField1.setBorder(new RoundedBorder(10, Tema.border(), 1.5f));
        jPasswordField1.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        jPasswordField1.setEchoChar('●');
        jPasswordField1.setText("");
        jPasswordField1.setBorder(new RoundedBorder(10, Tema.border(), 1.5f));
        jButton1.setFont(new Font("Segoe UI", Font.BOLD, 14));
        jButton1.setForeground(Color.WHITE);
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(true);

        // 3. Cursor de mão
        jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        // 4. Placeholder no campo email
        configurarPlaceholder(jTextField1, "ex: joao@email.com");

        // 5. Hover no botão ENTRAR
        adicionarHoverBotao();

        // 6. Botão toggle via JLayeredPane (sem tocar em layouts)
        criarBotaoToggle();

        // 7. Listener de mudança de tema
        Tema.addChangeListener(this::aplicarTema);

        // 8. Aplicar tema inicial
        aplicarTema();
    }

    /** Cria o botão toggle e posiciona-o no JLayeredPane do JFrame quando disponível. */
    private void criarBotaoToggle() {
        btnToggleTema = new JButton(Tema.isDark() ? "☀ Light" : "🌙 Dark");
        btnToggleTema.setFont(new Font("Segoe UI", Font.BOLD, 11));
        btnToggleTema.setFocusPainted(false);
        btnToggleTema.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnToggleTema.setSize(100, 28);

        btnToggleTema.addActionListener(e -> {
            Tema.toggleTheme();
            btnToggleTema.setText(Tema.isDark() ? "☀ Light" : "🌙 Dark");
        });

        addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(TelaEntrar.this);
                if (frame != null) {
                    JLayeredPane lp = frame.getLayeredPane();
                    btnToggleTema.setLocation(frame.getWidth() - 120, 10);
                    lp.add(btnToggleTema, JLayeredPane.PALETTE_LAYER);
                    lp.repaint();
                }
            }
            @Override public void ancestorRemoved(AncestorEvent event) {}
            @Override public void ancestorMoved(AncestorEvent event) {}
        });
    }

    /** Placeholder simples via FocusListener. */
    private void configurarPlaceholder(JTextField tf, String placeholder) {
        tf.setText(placeholder);
        tf.setForeground(Color.GRAY);
        tf.addFocusListener(new FocusAdapter() {
            @Override public void focusGained(FocusEvent e) {
                if (tf.getText().equals(placeholder)) {
                    tf.setText("");
                    tf.setForeground(Tema.text());
                }
            }
            @Override public void focusLost(FocusEvent e) {
                if (tf.getText().isEmpty()) {
                    tf.setText(placeholder);
                    tf.setForeground(Color.GRAY);
                }
            }
        });
    }

    /** Hover no botão ENTRAR: muda cor + texto. */
    private void adicionarHoverBotao() {
        jButton1.addMouseListener(new MouseAdapter() {
            @Override public void mouseEntered(MouseEvent e) {
                jButton1.setBackground(Tema.isDark() ? Tema.DARK_HOVER : new Color(0x3A56D4));
                jButton1.setText("ENTRAR  →");
            }
            @Override public void mouseExited(MouseEvent e) {
                jButton1.setBackground(Tema.primary());
                jButton1.setText("ENTRAR");
            }
            @Override public void mousePressed(MouseEvent e) {
                jButton1.setBackground(new Color(0x2A46C4));
            }
            @Override public void mouseReleased(MouseEvent e) {
                jButton1.setBackground(Tema.isDark() ? Tema.DARK_HOVER : new Color(0x3A56D4));
            }
        });
    }

    /** Re-aplica cores quando o tema muda. */
    private void aplicarTema() {
        setBackground(Tema.bg());
        jPanel1.setBackground(Tema.isDark() ? Tema.DARK_SURFACE : new Color(0x003399));

        jLabel7.setForeground(Tema.text());
        jLabel8.setForeground(Tema.text());
        jLabel9.setForeground(Tema.text());

        jTextField1.setBackground(Tema.isDark() ? new Color(0x1E293B) : Color.WHITE);
        jTextField1.setForeground(Tema.isDark() ? Tema.DARK_TEXT : Color.DARK_GRAY);
        jTextField1.setBorder(new RoundedBorder(10, Tema.border(), 1.5f));

        jPasswordField1.setBackground(Tema.isDark() ? new Color(0x1E293B) : Color.WHITE);
        jPasswordField1.setForeground(Tema.text());
        jPasswordField1.setBorder(new RoundedBorder(10, Tema.border(), 1.5f));

        jButton1.setBackground(Tema.primary());
        jButton1.setForeground(Color.WHITE);

        if (btnToggleTema != null) {
            btnToggleTema.setText(Tema.isDark() ? "☀ Light" : "🌙 Dark");
        }

        repaint();
        revalidate();
    }

    // =========================================================================
    // EVENTOS (prontos para implementar)
    // =========================================================================

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jPasswordField1.requestFocus();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email = jTextField1.getText();
        String senha = new String(jPasswordField1.getPassword());
        
        if (email.isEmpty() || email.equals("ex: joao@email.com")) {
            JOptionPane.showMessageDialog(this, "Por favor, insira o seu email.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira a sua senha.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // TODO: autenticar via DAO
        JOptionPane.showMessageDialog(this, "Autenticação em desenvolvimento...", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
